In [1]:
import chardet
import pandas as pd
import os

In [2]:
import numpy as np
import math

In [3]:
# 데이터 파일명을 리스트에 저장하기

error_files= os.listdir('C:/Users/USER/Desktop/산업인력공단 파일데이터 csv전체/오류데이터/통계데이터')

In [4]:
cd C:/Users/USER/Desktop/산업인력공단 파일데이터 csv전체/오류데이터/통계데이터

C:\Users\USER\Desktop\산업인력공단 파일데이터 csv전체\오류데이터\통계데이터

### 반복문을 이용해 여러 csv파일 한번에 read하기
1. 'df_error_files'라는 이름의 딕셔너리 생성(dict{})
2. 반복문을 이용해 파일명을 저장한 리스트 'error_files'에 파일명으로 접근 (인덱스 번호로 접근 X)
4. 파일 번호를 key값으로 사용하기 위해, 파일명 앞 두글자를 읽어들여 'file_num' 변수에 담음
5. csv파일을 읽어오는데, encoding 옵션을 'utf-8'로 해보고, 안되면 'cp949'로 하여 파일을 읽어 'df'변수에 담음
6. 미리 생성한 딕셔너리 'df_error_files'에 key값을 이용하여 담음 (형태: 'dictionary[key값] = value')
7. df_error_files의 key값들을 확인해 본 결과 데이터가 잘 들어간 것을 확인 할 수 있다

In [5]:
df_error_files= {}

for file in error_files:
    file_num= file[:2] 
    
    try:
        df= pd.read_csv(file, encoding='utf-8')
    except:
        df= pd.read_csv(file, encoding='cp949')
    
    df_error_files[file_num]= df

df_error_files.keys()

dict_keys(['04', '08', '24', '26', '27', '30'])

In [6]:
# 컬럼명 확인

df_error_files['24'].head(5)

,종목명,년도,성별,필기시험접수,필기시험응시,필기시험합격,필기시험합격률(%),실기시험접수,실기시험응시,실기시험합격,실기시험합격률(%),자격취득자현황(명)
0,산업기사합계,전체,전체,12159686,9348504,3039281,32.5,4780386,3957114,1772275,44.8,2102330
1,산업기사합계,2015(누적),전체,10757524,8272404,2633382,31.8,4151893,3421782,1518001,44.4,1841641
2,산업기사합계,2016,전체,279829,215050,74229,34.5,112506,96680,47488,49.1,48963
3,산업기사합계,2016,여자,48788,38727,16074,41.5,23440,19540,10699,54.8,10746
4,산업기사합계,2017,전체,280226,215033,77329,36.0,116697,100663,47739,47.4,49077

In [7]:
# 컬럼명 확인

df_error_files['30'].head(0)

Empty DataFrame
Columns: [종목명, 년도, 성별, 필기시험접수, 필기시험응시, 필기시험합격, 필기시험합격률, 실기시험접수, 실기시험응시, 실기시험합격, 실기시험합격률, 자격취득자현황(명)]
Index: []

In [8]:
# 30번 데이터의 컬럼명이 달라서 csv파일들과 반복문으로 적용이 안되기 때문에 컬럼명을 바꿔준다

df_error_files['30'].rename(columns={'필기시험합격률':'필기시험합격률(%)', '실기시험합격률':'실기시험합격률(%)'}, inplace=True)
df_error_files['30'].head(0)

Empty DataFrame
Columns: [종목명, 년도, 성별, 필기시험접수, 필기시험응시, 필기시험합격, 필기시험합격률(%), 실기시험접수, 실기시험응시, 실기시험합격, 실기시험합격률(%), 자격취득자현황(명)]
Index: []

### 반올림 함수 생성
round()함수의 경우 사사오입의 원칙이 적용되어, 반올림할 자리의 수가 홀수 이면 올림하지만 짝수일 경우 내림을 한다.  
따라서 사사오입의 원칙이 적용되지 않는 반올림을 구현하고 싶다면 함수를 직접생성해야 한다.
* 소수 둘째 자리에서 반올림하여 첫째 자리까지 표시할 것을 가정하고 만든 함수임을 유의
1. 원래 숫자에 10을 곱하여 소수점을 한칸 뒤로 이동시켜준다
2. 소수('multiply_num')에서 정수화 한 수('int(multiply_num)')을 빼주면 소수점 이하의 수만 남게 되는데, 이 때 소수점 이하의 수가 0.5 이상이면
3. 정수화 한 수에 1을 더해주고 더해준 수를 'roundup_num'이라는 변수에 저장한다
4. 0.5보다 작을 경우 그냥 정수화 한 수를 'roundup_num'이라는 변수에 저장한다
5. 함수 초반에 원래 수 'num'에 10을 곱해주었기 때문에, 원래의 소수점 위치로 이동시키기 위해 'roundup_num'을 다시 10으로 나누어준다
6. 계산 식을 'final_num'변수에 저장하여 return한다

In [111]:
def roundUp(num):
    roundup= []
    if math.isnan(num):
        rounup_num=0
    else:
        multiply_num= num*10
        if (multiply_num - int(multiply_num)) >= 0.5: 
            roundup_num= int(multiply_num) + 1 
        else: 
            roundup_num= int(multiply_num)
        roundup.append(roundup_num/10)
        
    to_return= pd.Series(roundup)
    return to_return

### 각 csv파일의 오류 확인 및 오류가 있는 행 추출

In [225]:
def find_error(file_num, which_file):
    # 한 파일 내 오류가 있는 행들을 저장할 딕셔너리 생성
    all_error_rows= {}
    
    print('파일 번호: ',file_num)
    
    check_examinees_num= (which_file['필기시험접수'] >= which_file['필기시험응시']) &  (which_file['필기시험응시'] >= which_file['필기시험합격']) & (which_file['실기시험접수'] >= which_file['실기시험응시']) &  (which_file['실기시험응시'] >= which_file['실기시험합격'])
    if False in check_examinees_num.unique():
        print('응시자수 오류 있음')
        # 응시자수에 오류가 있는 경우 'examinees_error_rows'를 key값으로 하여 딕셔너리에 추가
        all_error_rows['examinees_error_rows']=np.where(check_examinees_num ==False)[0]  
    else:
        print('응시자수 오류 없음')
     
    check_percentage= (which_file['필기시험합격률(%)'].iloc[0] == roundUp(which_file['필기시험합격'].iloc[0]/which_file['필기시험응시'].iloc[0]*100)) & (which_file['실기시험합격률(%)'].iloc[0] == roundUp(which_file['실기시험합격'].iloc[0]/which_file['실기시험응시'].iloc[0]*100))
    if False in check_percentage.unique():
        print('합격률 오류 있음')
        all_error_rows['percentage_error_rows']=np.where(check_percentage ==False)[0]
    else:
        print('합격률 오류 없음')
     
    # 응시자수, 합격률, 자격취득자 수 오류 행을들 저장한 딕셔너리를 하나의 데이터프레임으로 생성
    # 딕셔너리의 길이가 다르기 때문에 하나의 데이터프레임으로 만들기 위해 다음과 같이 작성
    if bool(all_error_rows):    
        return all_error_rows

In [226]:
def find_license_error_rows(file_num, which_file):
    check_license= which_file['자격취득자현황(명)'] <= which_file['실기시험합격']
    if False in check_license.unique():
        print('자격취득자 수가 실기시험합격자 수보다 많은 종목이 있습니다')
        license_error_rows=np.where(check_license ==False)[0]
        
    print('\n')
    
    return license_error_rows

In [227]:
# 각 csv파일 별로 오류가 있는 행을 정리한 데이터프레임을 파일 번호를 key값으로 하여 저장할 딕셔너리 생성
all_error_dfs= {}
license_error_lists={}

for key in df_error_files:    
    which_file= df_error_files[key].dropna()     # 계산 오류를 막기 위해 NaN값 미리 제거
    
    # NaN값을 제거 한 데이터 'which_file'과 key값을 함수 인자로 넣어줌
    # 함수의 return 값을 'errors_df'라는 변수로 받음
    errors_rows= find_error(key, which_file)    
    
    license_error_rows= find_license_error_rows(key, which_file)  
    license_error_lists[key]= list(license_error_rows)
    
    # 받은 return값을 'all_error_dfs' 딕셔너리에 추가
    # 이때 return받은 것은 해당 파일의 오류 행들을 모은 데이터 프레임
    # 각 파일의 파일 번호를 key값, 해당 데이터 프레임을 value로 하여 딕셔너리에 추가함
    if errors_rows is not None:
        all_error_dfs[key]= pd.DataFrame(errors_rows)
    
print(all_error_dfs.keys())
print(license_error_lists.keys())

파일 번호:  04
응시자수 오류 없음
합격률 오류 없음
자격취득자 수가 실기시험합격자 수보다 많은 종목이 있습니다


파일 번호:  08
응시자수 오류 없음
합격률 오류 없음
자격취득자 수가 실기시험합격자 수보다 많은 종목이 있습니다


파일 번호:  24
응시자수 오류 있음
합격률 오류 없음
자격취득자 수가 실기시험합격자 수보다 많은 종목이 있습니다


파일 번호:  26
응시자수 오류 없음
합격률 오류 없음
자격취득자 수가 실기시험합격자 수보다 많은 종목이 있습니다


파일 번호:  27
응시자수 오류 있음
합격률 오류 없음
자격취득자 수가 실기시험합격자 수보다 많은 종목이 있습니다


파일 번호:  30
응시자수 오류 없음
합격률 오류 없음
자격취득자 수가 실기시험합격자 수보다 많은 종목이 있습니다


dict_keys(['24', '27'])
dict_keys(['04', '08', '24', '26', '27', '30'])

In [241]:
print('04번 파일 전체 행: ', len(df_error_files['04']), '자격취득자 오류 행: ', len(license_error_lists['04']))
print('오류 행번호: \n', license_error_lists['04'],'\n\n')
print('08번 파일 전체 행: ', len(df_error_files['08']), '자격취득자 오류 행: ',len(license_error_lists['08']))
print('오류 행번호: \n', license_error_lists['08'],'\n\n')
print('24번 파일 전체 행: ', len(df_error_files['24']), '자격취득자 오류 행: ',len(license_error_lists['24']))
print('오류 행번호: \n', license_error_lists['24'],'\n\n')
print('26번 파일 전체 행: ', len(df_error_files['26']), '자격취득자 오류 행: ',len(license_error_lists['26']))
print('오류 행번호: \n', license_error_lists['26'],'\n\n')
print('27번 파일 전체 행: ', len(df_error_files['27']), '자격취득자 오류 행: ',len(license_error_lists['27']))
print('오류 행번호: \n', license_error_lists['27'],'\n\n')
print('30번 파일 전체 행: ', len(df_error_files['30']), '자격취득자 오류 행: ',len(license_error_lists['30']))
print('오류 행번호: \n', license_error_lists['30'],'\n\n')

04번 파일 전체 행:  1740 자격취득자 오류 행:  212
오류 행번호:
 [0, 1, 12, 13, 36, 37, 45, 48, 49, 81, 84, 85, 108, 109, 120, 121, 132, 133, 156, 157, 180, 181, 192, 193, 204, 205, 216, 217, 228, 229, 240, 241, 252, 253, 264, 265, 276, 277, 288, 289, 300, 301, 312, 313, 324, 325, 336, 337, 348, 349, 360, 361, 396, 397, 408, 409, 420, 421, 432, 433, 456, 457, 468, 469, 492, 493, 516, 517, 540, 541, 552, 553, 564, 565, 576, 577, 588, 589, 600, 601, 612, 613, 636, 637, 648, 649, 672, 673, 684, 685, 696, 697, 708, 709, 720, 721, 732, 733, 741, 743, 744, 745, 756, 757, 777, 791, 792, 793, 804, 805, 828, 829, 840, 841, 852, 853, 864, 865, 876, 877, 888, 889, 911, 912, 956, 957, 980, 981, 992, 993, 1004, 1005, 1028, 1029, 1052, 1053, 1100, 1101, 1112, 1113, 1124, 1125, 1153, 1154, 1165, 1166, 1177, 1178, 1201, 1202, 1249, 1250, 1261, 1262, 1273, 1274, 1285, 1286, 1297, 1298, 1321, 1322, 1333, 1334, 1357, 1358, 1369, 1370, 1401, 1402, 1413, 1414, 1437, 1438, 1449, 1450, 1461, 1462, 1485, 1486, 1497, 1498, 1509, 1510, 1521, 1522, 1533, 1534, 1545, 1546, 1572, 1573, 1584, 1585, 1596, 1597, 1620, 1621, 1632, 1633, 1644, 1645, 1656, 1657, 1668, 1669, 1692, 1693, 1704, 1705, 1716, 1717]


08번 파일 전체 행:  1494 자격취득자 오류 행:  158
오류 행번호:
 [0, 1, 12, 13, 24, 25, 36, 37, 84, 85, 96, 97, 108, 109, 122, 123, 146, 147, 158, 159, 170, 171, 182, 183, 194, 195, 206, 207, 218, 219, 230, 231, 242, 243, 254, 255, 304, 305, 318, 319, 332, 333, 344, 345, 356, 357, 368, 369, 392, 393, 404, 405, 456, 457, 474, 475, 476, 477, 488, 489, 504, 505, 516, 517, 528, 529, 564, 565, 578, 579, 594, 595, 606, 607, 618, 619, 630, 631, 642, 643, 678, 679, 692, 693, 706, 707, 718, 719, 730, 731, 766, 767, 778, 779, 790, 791, 806, 807, 822, 823, 844, 845, 870, 871, 882, 883, 896, 897, 932, 933, 958, 959, 984, 985, 998, 999, 1012, 1013, 1038, 1039, 1050, 1051, 1062, 1063, 1074, 1075, 1086, 1087, 1098, 1099, 1122, 1123, 1170, 1171, 1220, 1221, 1232, 1233, 1244, 1245, 1256, 1257, 1280, 1281, 1354, 1355, 1366, 1367, 1428, 1429, 1440, 1441, 1452, 1453, 1454, 1455, 1456, 1457]


24번 파일 전체 행:  2392 자격취득자 오류 행:  857
오류 행번호:
 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 26, 27, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 70, 71, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 95, 102, 103, 114, 115, 126, 127, 140, 141, 152, 153, 154, 155, 156, 157, 158, 159, 162, 164, 166, 168, 169, 178, 179, 180, 181, 182, 183, 184, 185, 190, 191, 192, 193, 194, 195, 196, 197, 198, 200, 201, 210, 211, 212, 213, 214, 216, 217, 238, 239, 240, 241, 242, 243, 244, 245, 250, 251, 252, 254, 255, 256, 257, 272, 273, 274, 275, 276, 277, 278, 279, 284, 285, 286, 287, 288, 289, 290, 292, 293, 294, 296, 297, 298, 300, 302, 304, 306, 310, 311, 312, 313, 314, 315, 316, 318, 319, 320, 322, 323, 336, 337, 340, 344, 348, 349, 352, 353, 354, 356, 372, 373, 378, 379, 392, 393, 394, 416, 417, 418, 430, 431, 442, 443, 454, 455, 504, 505, 516, 517, 518, 519, 522, 523, 526, 527, 530, 531, 542, 543, 554, 555, 556, 557, 568, 569, 580, 581, 584, 586, 588, 590, 592, 593, 596, 598, 600, 602, 606, 607, 610, 611, 612, 613, 618, 619, 620, 621, 632, 633, 644, 645, 662, 663, 668, 669, 670, 672, 673, 674, 675, 676, 677, 678, 690, 691, 692, 693, 694, 695, 696, 697, 698, 699, 700, 704, 705, 706, 708, 710, 712, 714, 716, 718, 720, 722, 724, 726, 744, 745, 746, 747, 766, 767, 768, 769, 770, 771, 772, 773, 774, 775, 776, 777, 778, 779, 780, 781, 782, 784, 785, 786, 787, 788, 789, 790, 791, 792, 793, 796, 798, 800, 802, 806, 807, 808, 810, 812, 814, 816, 818, 819, 832, 833, 846, 847, 848, 850, 852, 853, 854, 856, 858, 859, 860, 862, 863, 864, 866, 867, 868, 884, 885, 886, 888, 890, 892, 894, 895, 896, 897, 898, 900, 914, 915, 916, 917, 920, 921, 924, 925, 932, 933, 944, 945, 962, 963, 974, 975, 986, 987, 990, 991, 992, 993, 994, 995, 996, 997, 998, 999, 1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011, 1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035, 1036, 1037, 1038, 1042, 1043, 1044, 1046, 1048, 1050, 1052, 1054, 1055, 1056, 1058, 1060, 1062, 1064, 1066, 1067, 1070, 1078, 1079, 1080, 1081, 1082, 1083, 1094, 1095, 1096, 1097, 1108, 1109, 1110, 1111, 1126, 1127, 1128, 1129, 1130, 1131, 1132, 1133, 1136, 1137, 1138, 1139, 1142, 1143, 1148, 1149, 1150, 1151, 1152, 1153, 1156, 1157, 1158, 1159, 1160, 1162, 1166, 1168, 1172, 1173, 1174, 1176, 1180, 1182, 1190, 1191, 1192, 1198, 1200, 1202, 1203, 1204, 1210, 1212, 1214, 1215, 1216, 1217, 1218, 1219, 1220, 1221, 1222, 1223, 1224, 1225, 1226, 1228, 1229, 1230, 1231, 1232, 1233, 1234, 1235, 1236, 1237, 1238, 1240, 1241, 1252, 1253, 1264, 1265, 1268, 1269, 1278, 1279, 1282, 1283, 1286, 1287, 1301, 1302, 1303, 1304, 1305, 1306, 1309, 1310, 1311, 1312, 1313, 1314, 1315, 1316, 1317, 1318, 1319, 1320, 1321, 1322, 1323, 1324, 1325, 1326, 1327, 1328, 1329, 1330, 1331, 1332, 1333, 1334, 1335, 1336, 1343, 1344, 1355, 1356, 1359, 1360, 1361, 1362, 1377, 1378, 1379, 1380, 1385, 1386, 1405, 1406, 1407, 1408, 1409, 1410, 1411, 1412, 1413, 1414, 1415, 1416, 1429, 1430, 1431, 1432, 1433, 1434, 1435, 1436, 1437, 1438, 1439, 1440, 1441, 1442, 1443, 1444, 1445, 1446, 1447, 1448, 1449, 1450, 1451, 1452, 1453, 1454, 1458, 1459, 1460, 1462, 1464, 1466, 1468, 1482, 1483, 1484, 1486, 1488, 1490, 1492, 1494, 1495, 1496, 1498, 1500, 1502, 1504, 1508, 1509, 1520, 1521, 1522, 1523, 1524, 1525, 1526, 1527, 1528, 1529, 1530, 1544, 1545, 1546, 1548, 1549, 1550, 1552, 1554, 1593, 1594, 1595, 1596, 1597, 1598, 1599, 1600, 1601, 1602, 1603, 1607, 1608, 1609, 1610, 1611, 1612, 1613, 1614, 1615, 1616, 1617, 1618, 1619, 1620, 1621, 1622, 1626, 1633, 1634, 1635, 1636, 1637, 1638, 1639, 1640, 1641, 1642, 1643, 1644, 1661, 1662, 1673, 1674, 1685, 1686, 1697, 1698, 1705, 1706, 1707, 1708, 1709, 1710, 1713, 1714, 1721, 1722, 1723, 1724, 1737, 1738, 1745, 1747, 1748, 1749, 1750, 1761, 1762, 1777, 1778, 1779, 1780, 1805, 1806, 1811, 1812, 1821, 1822, 1825, 1826, 1829, 1835, 1836, 1837, 1840, 1841, 1842, 1843, 1854, 1855, 1858, 1868, 1869, 1870, 1871, 1875, 1876, 1882, 1883, 1890, 1891, 1892, 1893, 1896, 1897, 1898, 1899, 1908, 1909, 1910, 1911, 1924, 1925, 1938, 1941, 1942, 1945, 1946, 1947, 1948, 1949, 1950, 1961, 1962, 1973, 1974, 1983, 1984, 1988, 1989, 1990, 1991, 1992, 1993, 2004, 2005, 2036, 2037, 2048, 2049, 2072, 2073, 2084, 2085, 2096, 2097, 2120, 2121, 2132, 2133, 2144, 2145, 2156, 2157, 2170, 2171, 2172, 2173, 2174, 2175, 2176, 2178, 2180, 2181, 2184, 2185, 2186, 2187, 2188, 2190, 2192, 2193, 2230, 2231, 2236, 2237, 2238, 2239, 2240, 2241, 2242, 2243, 2246, 2247, 2248, 2249, 2250, 2251, 2262, 2263, 2276, 2277, 2288, 2289, 2312, 2313, 2338, 2339, 2350, 2351, 2352, 2354, 2355, 2356, 2357, 2358, 2359, 2360, 2374, 2375, 2376, 2377, 2378, 2379, 2380, 2382, 2383, 2384, 2385, 2386, 2387, 2388]


26번 파일 전체 행:  598 자격취득자 오류 행:  24
오류 행번호:
 [130, 131, 142, 143, 250, 251, 274, 275, 310, 311, 322, 323, 334, 335, 346, 347, 358, 359, 370, 371, 442, 443, 562, 563]


27번 파일 전체 행:  2436 자격취득자 오류 행:  1411
오류 행번호:
 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 60, 61, 72, 73, 84, 85, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 237, 238, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 265, 266, 267, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 303, 304, 305, 306, 307, 308, 309, 310, 311, 313, 315, 316, 317, 319, 321, 322, 333, 334, 335, 336, 337, 338, 339, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 369, 370, 371, 372, 373, 374, 375, 376, 377, 379, 381, 382, 393, 394, 395, 397, 399, 401, 402, 403, 405, 406, 414, 417, 418, 419, 421, 422, 423, 425, 426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 453, 454, 455, 456, 457, 459, 461, 462, 463, 465, 466, 477, 478, 501, 502, 503, 504, 505, 506, 507, 508, 509, 511, 512, 513, 514, 525, 526, 527, 528, 529, 530, 531, 533, 535, 537, 538, 549, 550, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571, 572, 585, 586, 587, 588, 589, 590, 591, 592, 593, 597, 598, 599, 600, 601, 602, 603, 604, 605, 609, 610, 611, 613, 615, 617, 619, 621, 622, 623, 625, 627, 629, 631, 633, 634, 635, 636, 637, 638, 639, 640, 641, 642, 643, 644, 645, 646, 657, 658, 681, 682, 683, 684, 685, 686, 687, 688, 689, 690, 691, 692, 693, 694, 695, 696, 697, 698, 699, 700, 701, 702, 703, 704, 705, 706, 707, 708, 709, 710, 711, 712, 713, 714, 715, 716, 717, 718, 729, 730, 731, 732, 733, 734, 735, 736, 737, 738, 739, 740, 741, 742, 743, 745, 746, 747, 748, 749, 750, 751, 752, 753, 754, 755, 756, 757, 758, 759, 760, 761, 762, 763, 764, 765, 766, 777, 778, 789, 790, 801, 802, 813, 814, 825, 826, 827, 828, 829, 830, 831, 832, 833, 835, 836, 837, 838, 839, 840, 841, 843, 845, 847, 849, 850, 851, 853, 855, 857, 859, 861, 862, 873, 874, 875, 876, 877, 879, 881, 883, 885, 886, 897, 898, 899, 900, 901, 902, 903, 904, 905, 907, 908, 909, 910, 911, 913, 915, 917, 919, 923, 924, 925, 926, 927, 928, 929, 930, 931, 932, 945, 946, 947, 949, 950, 951, 952, 953, 954, 955, 957, 958, 959, 961, 962, 963, 965, 967, 969, 970, 971, 973, 975, 977, 979, 981, 982, 983, 985, 986, 987, 988, 989, 991, 993, 994, 995, 996, 997, 998, 999, 1001, 1002, 1003, 1004, 1029, 1030, 1031, 1033, 1035, 1037, 1039, 1041, 1042, 1053, 1054, 1065, 1066, 1077, 1078, 1079, 1081, 1082, 1083, 1085, 1087, 1088, 1089, 1090, 1091, 1093, 1094, 1095, 1097, 1099, 1100, 1101, 1102, 1103, 1105, 1107, 1109, 1111, 1113, 1114, 1125, 1126, 1127, 1128, 1129, 1130, 1131, 1132, 1133, 1134, 1135, 1136, 1137, 1138, 1139, 1140, 1141, 1142, 1143, 1144, 1145, 1146, 1147, 1148, 1149, 1150, 1151, 1152, 1153, 1154, 1155, 1156, 1157, 1158, 1159, 1160, 1161, 1162, 1163, 1164, 1165, 1166, 1167, 1168, 1169, 1170, 1171, 1172, 1173, 1174, 1175, 1176, 1177, 1179, 1180, 1181, 1182, 1183, 1184, 1185, 1186, 1187, 1188, 1189, 1190, 1191, 1192, 1193, 1194, 1195, 1196, 1197, 1198, 1199, 1200, 1201, 1202, 1203, 1204, 1205, 1206, 1207, 1208, 1209, 1210, 1211, 1213, 1215, 1217, 1218, 1219, 1221, 1222, 1223, 1225, 1227, 1229, 1231, 1233, 1234, 1235, 1237, 1239, 1241, 1243, 1245, 1246, 1247, 1249, 1251, 1253, 1255, 1257, 1258, 1261, 1263, 1264, 1267, 1269, 1270, 1281, 1282, 1285, 1287, 1288, 1291, 1293, 1294, 1305, 1306, 1317, 1318, 1329, 1330, 1341, 1342, 1343, 1345, 1347, 1349, 1351, 1353, 1354, 1355, 1357, 1359, 1361, 1363, 1365, 1366, 1389, 1390, 1391, 1393, 1394, 1395, 1397, 1399, 1401, 1402, 1403, 1405, 1406, 1407, 1409, 1411, 1413, 1414, 1415, 1417, 1419, 1421, 1423, 1425, 1426, 1427, 1429, 1430, 1431, 1432, 1433, 1435, 1436, 1437, 1438, 1439, 1441, 1443, 1445, 1447, 1449, 1450, 1451, 1453, 1454, 1455, 1456, 1457, 1459, 1460, 1461, 1462, 1463, 1464, 1465, 1466, 1467, 1468, 1469, 1470, 1471, 1472, 1473, 1474, 1475, 1477, 1478, 1479, 1481, 1483, 1484, 1485, 1486, 1487, 1489, 1491, 1492, 1493, 1495, 1497, 1498, 1499, 1500, 1501, 1502, 1503, 1504, 1505, 1506, 1507, 1508, 1509, 1510, 1511, 1521, 1522, 1523, 1533, 1534, 1535, 1536, 1537, 1538, 1539, 1540, 1541, 1542, 1543, 1544, 1545, 1546, 1547, 1548, 1549, 1550, 1551, 1552, 1553, 1554, 1555, 1556, 1557, 1558, 1569, 1570, 1581, 1582, 1593, 1594, 1595, 1596, 1597, 1598, 1599, 1600, 1601, 1602, 1603, 1604, 1605, 1606, 1607, 1608, 1609, 1610, 1611, 1612, 1613, 1614, 1615, 1616, 1617, 1618, 1629, 1630, 1631, 1632, 1635, 1636, 1639, 1640, 1641, 1642, 1643, 1644, 1645, 1646, 1647, 1648, 1649, 1650, 1651, 1652, 1653, 1654, 1664, 1665, 1666, 1667, 1668, 1669, 1670, 1671, 1672, 1673, 1674, 1675, 1676, 1677, 1678, 1689, 1690, 1691, 1692, 1693, 1694, 1695, 1696, 1697, 1698, 1699, 1700, 1701, 1702, 1703, 1704, 1705, 1706, 1707, 1708, 1709, 1710, 1711, 1712, 1725, 1726, 1727, 1728, 1729, 1730, 1731, 1732, 1733, 1735, 1737, 1738, 1739, 1740, 1741, 1742, 1743, 1744, 1745, 1746, 1747, 1748, 1749, 1750, 1751, 1752, 1753, 1754, 1755, 1756, 1757, 1758, 1759, 1760, 1778, 1779, 1780, 1781, 1782, 1783, 1784, 1785, 1786, 1787, 1788, 1789, 1790, 1791, 1792, 1793, 1794, 1795, 1796, 1797, 1798, 1799, 1800, 1801, 1802, 1803, 1804, 1805, 1806, 1807, 1808, 1809, 1810, 1811, 1812, 1813, 1814, 1815, 1824, 1826, 1827, 1836, 1838, 1839, 1850, 1851, 1860, 1861, 1874, 1875, 1884, 1885, 1886, 1887, 1896, 1897, 1898, 1899, 1910, 1911, 1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1936, 1937, 1938, 1939, 1940, 1941, 1942, 1943, 1944, 1945, 1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2025, 2027, 2029, 2031, 2033, 2034, 2035, 2036, 2037, 2038, 2039, 2040, 2041, 2043, 2044, 2045, 2046, 2047, 2048, 2049, 2050, 2051, 2052, 2053, 2054, 2055, 2056, 2057, 2058, 2059, 2060, 2061, 2062, 2063, 2064, 2065, 2066, 2067, 2068, 2069, 2070, 2071, 2073, 2074, 2075, 2077, 2078, 2079, 2080, 2081, 2082, 2083, 2084, 2085, 2086, 2087, 2088, 2089, 2090, 2091, 2092, 2093, 2094, 2095, 2097, 2099, 2100, 2103, 2104, 2117, 2118, 2119, 2120, 2121, 2122, 2123, 2124, 2125, 2126, 2127, 2128, 2141, 2142, 2144, 2153, 2154, 2155, 2156, 2157, 2158, 2159, 2160, 2161, 2162, 2163, 2164, 2165, 2166, 2177, 2178, 2189, 2190, 2201, 2202, 2213, 2214, 2225, 2226, 2237, 2238, 2249, 2250, 2261, 2262, 2273, 2274, 2285, 2286, 2297, 2298, 2299, 2301, 2302, 2303, 2305, 2306, 2307, 2308, 2309, 2310, 2311, 2313, 2314, 2315, 2317, 2318, 2319, 2320, 2321, 2322, 2323, 2324, 2325, 2326, 2327, 2328, 2329, 2330, 2331, 2332, 2333, 2334, 2335, 2337, 2339, 2341, 2343, 2345, 2346, 2357, 2358, 2359, 2360, 2361, 2363, 2365, 2367, 2369, 2370, 2371, 2372, 2373, 2374, 2375, 2376, 2377, 2378, 2379, 2380, 2381, 2382, 2383, 2384, 2385, 2386, 2387, 2388, 2389, 2390, 2391, 2392, 2393, 2394, 2395, 2396, 2397, 2398, 2399, 2400, 2401, 2402, 2404, 2405, 2406, 2408, 2409, 2410, 2411, 2424, 2425, 2426, 2428, 2429, 2430, 2432, 2433, 2434, 2435]


30번 파일 전체 행:  410 자격취득자 오류 행:  23
오류 행번호:
 [2, 3, 5, 8, 9, 122, 123, 128, 129, 152, 153, 158, 159, 162, 163, 168, 169, 172, 173, 178, 179, 265, 285]

In [216]:
print(all_error_dfs)

{'24':    examinees_error_rows
0                  2234
1                  2235, '27':    examinees_error_rows
0                   453
1                   454
2                  1557
3                  1558}

In [130]:
print(df_error_files['24'].iloc[2234, :])
print(df_error_files['24'].iloc[2235, :])

종목명           비파괴검사(구)
년도                  전체
성별                  전체
필기시험접수             542
필기시험응시             469
필기시험합격             177
필기시험합격률(%)        37.7
실기시험접수             198
실기시험응시             209
실기시험합격             121
실기시험합격률(%)        57.9
자격취득자현황(명)           0
Name: 2234, dtype: object
종목명           비파괴검사(구)
년도            2015(누적)
성별                  전체
필기시험접수             542
필기시험응시             469
필기시험합격             177
필기시험합격률(%)        37.7
실기시험접수             198
실기시험응시             209
실기시험합격             121
실기시험합격률(%)        57.9
자격취득자현황(명)           0
Name: 2235, dtype: object

In [134]:
print(df_error_files['27'].iloc[453, :])
print(df_error_files['27'].iloc[454, :])
print(df_error_files['27'].iloc[1557, :])
print(df_error_files['27'].iloc[1558, :])

종목명               측량
시작 연도           1975
완료 연도           2019
성별                전체
필기시험접수        245169
필기시험응시        211651
필기시험합격         42477
필기시험합격률(%)      20.1
실기시험접수        130344
실기시험응시        133067
실기시험합격         83795
실기시험합격률(%)      63.0
자격취득자현황(명)     95704
Name: 453, dtype: object
종목명               측량
시작 연도           1975
완료 연도           2014
성별                전체
필기시험접수        231988
필기시험응시        200823
필기시험합격         37945
필기시험합격률(%)      18.9
실기시험접수        118012
실기시험응시        121216
실기시험합격         73611
실기시험합격률(%)      60.7
자격취득자현황(명)     85157
Name: 454, dtype: object
종목명            섬유분야
시작 연도          1975
완료 연도          2019
성별               전체
필기시험접수        15958
필기시험응시        14536
필기시험합격         3477
필기시험합격률(%)     23.9
실기시험접수        35461
실기시험응시        36686
실기시험합격        34269
실기시험합격률(%)     93.4
자격취득자현황(명)    40617
Name: 1557, dtype: object
종목명            섬유분야
시작 연도          1975
완료 연도          2014
성별               전체
필기시험접수        15851
필기시험응시        14458
필기시험합격         3450
필기시험합격률(%)     23.9
실기시험접수        34059
실기시험응시        35301
실기시험합격        32889
실기시험합격률(%)     93.2
자격취득자현황(명)    39237
Name: 1558, dtype: object

<br>
<br>
<br>
<br>
<br>

### 코드 테스트

#### 데이터 파일명이 리스트로 잘 들어갔는지 확인

In [9]:
error_files

['04. 직무분야별 기사 자격통계현황_20200623.csv',
 '08. 직무분야별 기술사 자격통계현황_20210621.csv',
 '24. 직무분야별 산업기사 자격통계현황_20200622.csv',
 '26. 직무분야별 기능장 자격통계현황_20200623.csv',
 '27. 직무분야별 기능사 자격통계현황_20200623.csv',
 '30. 직무분야별 전문사무 자격통계현황_20210621.csv']

In [10]:
error_files[0]

'04. 직무분야별 기사 자격통계현황_20200623.csv'

#### csv 파일의 인코딩 형식 확인 방법

In [148]:
print(chardet.detect(error_files[0].encode()))
print(type(chardet.detect(error_files[0].encode())))
print(chardet.detect(error_files[0].encode())['encoding'])

{'encoding': 'utf-8', 'confidence': 0.99, 'language': ''}
<class 'dict'>
utf-8

#### 컬럼간에 여러 조건을 적용했을 때 boolean type 출력값이 제대로 나오는지 확인

In [11]:
(df_error_files['04']['필기시험응시'] >= df_error_files['04']['필기시험합격']) & (df_error_files['04']['필기시험접수'] >= df_error_files['04']['필기시험응시'] )

0       True
1       True
2       True
3       True
4       True
        ...
1735    True
1736    True
1737    True
1738    True
1739    True
Length: 1740, dtype: bool

In [12]:
type(df_error_files['30']['필기시험합격']/df_error_files['30']['필기시험응시']*100)

pandas.core.series.Series

In [13]:
temp= ((df_error_files['30']['필기시험응시'] >= df_error_files['30']['필기시험합격']) & (df_error_files['30']['필기시험접수'] >= df_error_files['30']['필기시험응시'] )).unique()
print(temp)
print(type(temp))

[ True]
<class 'numpy.ndarray'>

In [14]:
if False in temp:
    print('false')
else:
    print('true')

true

#### 컬럼 간 계산 bool type 확인
* 컬럼 전체가 한번에 계산되는지 확인
* 반올림 해야함 'round(값, 소수점 자릿수)'

In [208]:
df_error_files['04']['필기시험합격률(%)'] == round(df_error_files['04']['필기시험합격']/df_error_files['04']['필기시험응시']*100,1)

0       True
1       True
2       True
3       True
4       True
        ...
1735    True
1736    True
1737    True
1738    True
1739    True
Length: 1740, dtype: bool

In [210]:
print(file_num)
print(which_file)

30
               종목명    년도  성별  필기시험접수  필기시험응시  필기시험합격  필기시험합격률(%)  실기시험접수  \
0           전문사무합계  2016  전체  547704  374193  197851        52.9  414328
1           전문사무합계  2016  여자  329069  223763  115730        51.7  239512
2           전문사무합계  2017  전체  548405  445803  193868        43.5  403801
3           전문사무합계  2017  여자  329360  265421  113101        42.6  235846
4           전문사무합계  2018  전체  597348  479424  226538        47.3  478234
..             ...   ...  ..     ...     ...     ...         ...     ...
405  멀티미디어콘텐츠제작전문가  2018  여자     526     408     186        45.6     232
406  멀티미디어콘텐츠제작전문가  2019  전체    1102     815     526        64.5     548
407  멀티미디어콘텐츠제작전문가  2019  여자     543     402     247        61.4     253
408  멀티미디어콘텐츠제작전문가  2020  전체    1079     884     444        50.2     571
409  멀티미디어콘텐츠제작전문가  2020  여자     555     456     233        51.1     286

     실기시험응시  실기시험합격  실기시험합격률(%)  자격취득자현황(명)
0    401267  137769        34.3      137769
1    230240   82068        35.6       82068
2    346417  133024        38.4      135538
3    201794   78463        38.9       80602
4    409760  139548        34.1      139548
..      ...     ...         ...         ...
405     190      93        48.9          93
406     420     163        38.8         163
407     194      70        36.1          70
408     463     341        73.7         341
409     232     174        75.0         174

[410 rows x 12 columns]

#### 오류가 있는 행 번호 찾기

In [236]:
print(check_examinees_num.unique())
print(check_percentage.unique())
print(check_license.unique())

[ True]
[ True False]
[False  True]

In [256]:
print(type(check_examinees_num))
print(type(check_examinees_num.unique()))
print(type(np.where(check_percentage ==False)))

<class 'pandas.core.series.Series'>
<class 'numpy.ndarray'>
<class 'tuple'>

In [251]:
print(np.where(check_percentage ==False))
print(check_percentage[check_percentage ==False])

(array([ 45, 164, 165, 166, 167, 170, 171, 172, 173, 174, 175, 176, 177,
       178, 179, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200,
       201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213,
       214, 215, 216, 217, 218, 219, 307, 377], dtype=int64),)
45     False
164    False
165    False
166    False
167    False
170    False
171    False
172    False
173    False
174    False
175    False
176    False
177    False
178    False
179    False
190    False
191    False
192    False
193    False
194    False
195    False
196    False
197    False
198    False
199    False
200    False
201    False
202    False
203    False
204    False
205    False
206    False
207    False
208    False
209    False
210    False
211    False
212    False
213    False
214    False
215    False
216    False
217    False
218    False
219    False
307    False
377    False
dtype: bool

In [283]:
a= np.where(check_percentage ==False)[0]
a[0]

45

#### 찾은 행 번호를 리스트 형태로 받기 위해서
1. np.where을 사용하여 값을 찾으면 tuple형태로 결과가 반환되며, 모든 행 번호가 '0'인덱스에 다 들어있음
2. np.where의 결과값으로 나온 tuple을 인덱싱 하여 '0'인덱스 값을 새로운 변수(error_rows)에 저장
3. 'error_rows'에는 행 번호가 numpy array형식으로 저장됨
4. 'error_rows'의 데이터가 인덱싱 하여 행 번호를 하나씩 확인할 수 있음

In [262]:
tmp= np.where(check_percentage ==False)
print(tmp)
print(type(tmp))

(array([ 45, 164, 165, 166, 167, 170, 171, 172, 173, 174, 175, 176, 177,
       178, 179, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200,
       201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213,
       214, 215, 216, 217, 218, 219, 307, 377], dtype=int64),)
<class 'tuple'>

In [287]:
error_rows=np.where(check_percentage ==False)[0]
print(type(np.where(check_percentage ==False)))
print(type(error_rows))
print(error_rows)
print(error_rows[0])

<class 'tuple'>
<class 'numpy.ndarray'>
[ 45 164 165 166 167 170 171 172 173 174 175 176 177 178 179 190 191 192
 193 194 195 196 197 198 199 200 201 202 203 204 205 206 207 208 209 210
 211 212 213 214 215 216 217 218 219 307 377]
45

In [351]:
def roundUp(num):
    multiply_num= num*10
    if (multiply_num - int(multiply_num)) >= 0.5: 
        roundup_num= int(multiply_num) + 1 
    else: 
        roundup_num= int(multiply_num)
        
    final_num= roundup_num/10
    return final_num

roundUp(81.25)

81.3

#### nan값이 왜 나오는지 계산테스트

In [131]:
df_error_files['08'].iloc[1493, 10]/df_error_files['08'].iloc[1493, 9]*100

C:\Users\USER\AppData\Local\Temp/ipykernel_8724/660015549.py:1: RuntimeWarning: invalid value encountered in double_scalars
  df_error_files['08'].iloc[1493, 10]/df_error_files['08'].iloc[1493, 9]*100

nan

In [132]:
df_error_files['08'].iloc[1493, 10]

0.0

In [133]:
0/0*100

ZeroDivisionError: division by zero